// <auto-generated />
namespace EFAssignment1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsernameandBirthDateadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsernameandBirthDateadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202108240334572_Username and BirthDate added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
